### Read Image description file

In [43]:
filename = "Descriptions_File_csv.csv"
import pandas as pd 
df = pd.read_csv(filename, encoding='utf-8')

df.head()

images                                             labels
0  db4a2b00-066f26b4.jpg                There are some cars in front of you
1  d8699e8e-52790a22.jpg               There is a stop sign in front of you
2  cd7dff46-00000000.jpg                There are some cars in front of you
3  f6f90595-b5a7a6d3.jpg                     There is a bus in front of you
4  b5050293-00000000.jpg  There are some cars buses stop signs speed lim...

### Prepare image features

In [44]:
imagefiles_list = []
from PIL import Image
import numpy as np

for i in range(len(df)):
    imagefiles_list.append(df['images'][i])
    
size = (224,224)
x = np.array([np.array(Image.open("./test/"+fname).resize(size).convert('RGB')) for fname in imagefiles_list])
print(x.shape)

(566, 224, 224, 3)


### Image Labels

In [45]:
labels = df['labels']
labels = pd.get_dummies(labels).as_matrix()
print(labels[:5])
print(labels.shape)

[[0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0]]
(566, 12)


### Image Classification Model 

In [48]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout, Flatten
from keras.layers import Conv2D
from keras.layers import MaxPooling2D


input_shape = (224, 224, 3)

model = Sequential([
    Conv2D(64, (3, 3), input_shape=input_shape, padding='same',
           activation='relu'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D(pool_size=(2, 2), strides=(2, 2)),
    Conv2D(128, (3, 3), activation='relu', padding='same'),
    Conv2D(128, (3, 3), activation='relu', padding='same',),
    MaxPooling2D(pool_size=(2, 2), strides=(2, 2)),
    Conv2D(256, (3, 3), activation='relu', padding='same',),
    Conv2D(256, (3, 3), activation='relu', padding='same',),
    Conv2D(256, (3, 3), activation='relu', padding='same',),
    MaxPooling2D(pool_size=(2, 2), strides=(2, 2)),
    Conv2D(512, (3, 3), activation='relu', padding='same',),
    Conv2D(512, (3, 3), activation='relu', padding='same',),
    Conv2D(512, (3, 3), activation='relu', padding='same',),
    MaxPooling2D(pool_size=(2, 2), strides=(2, 2)),
    Conv2D(512, (3, 3), activation='relu', padding='same',),
    Conv2D(512, (3, 3), activation='relu', padding='same',),
    Conv2D(512, (3, 3), activation='relu', padding='same',),
    MaxPooling2D(pool_size=(2, 2), strides=(2, 2)),
    Flatten(),
    Dense(4096, activation='relu'),
    Dense(4096, activation='relu'),
    Dense(12, activation='softmax')
])

model.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_14 (Conv2D)           (None, 224, 224, 64)      1792      
_________________________________________________________________
conv2d_15 (Conv2D)           (None, 224, 224, 64)      36928     
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 112, 112, 64)      0         
_________________________________________________________________
conv2d_16 (Conv2D)           (None, 112, 112, 128)     73856     
_________________________________________________________________
conv2d_17 (Conv2D)           (None, 112, 112, 128)     147584    
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 (None, 56, 56, 128)       0         
_________________________________________________________________
conv2d_18 (Conv2D)           (None, 56, 56, 256)       295168    
__________

In [ ]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x, labels, epochs=10, batch_size=32)

Epoch 1/10
 64/566 [==>...........................] - ETA: 11:02 - loss: 7.6305 - acc: 0.1094    